import { useState } from 'react';
import type { AppDatabase, AppSettings } from '../../domain/model';
import { DataSettingsPanel } from './DataSettingsPanel';
import { TimerSettingsPanel } from './TimerSettingsPanel';
interface Props{database:AppDatabase;onClose:()=>void;onReset:()=>Promise<void>;onUpdateSettings:(patch:{restTimer?:Partial<AppSettings['restTimer']>})=>Promise<void>}
type Screen='root'|'workout'|'timer'|'units'|'notifications'|'data'|'accessibility'|'about';
const titles:Record<Screen,string>={root:'Settings',workout:'Workout',timer:'Rest timer',units:'Units & measurements',notifications:'Notifications & feedback',data:'Data',accessibility:'Accessibility',about:'About & diagnostics'};
function Row({title,detail,onClick}:{title:string;detail:string;onClick:()=>void}){return <button className="settings-navigation-row" type="button" onClick={onClick}><span><strong>{title}</strong><small>{detail}</small></span><i>›</i></button>}
export function SettingsSheetV2({database,onClose,onReset,onUpdateSettings}:Props){const[screen,setScreen]=useState<Screen>('root');const backTarget:Screen=screen==='timer'?'workout':'root';return <div className="modal-backdrop settings-backdrop" onMouseDown={onClose}><aside className="settings-sheet" onMouseDown={e=>e.stopPropagation()}><header><div className="settings-title-row">{screen!=='root'&&<button className="settings-back-button" onClick={()=>setScreen(backTarget)}>‹</button>}<div><p className="eyebrow">Settings</p><h2>{titles[screen]}</h2></div></div><button className="icon-button" onClick={onClose}>×</button></header>
{screen==='root'&&<nav className="settings-navigation"><Row title="Workout" detail="Rest timer, set entry and session behaviour" onClick={()=>setScreen('workout')}/><Row title="Units & measurements" detail={`${database.profile.units.toUpperCase()} · body history`} onClick={()=>setScreen('units')}/><Row title="Notifications & feedback" detail="Sound, vibration and Android delivery" onClick={()=>setScreen('notifications')}/><Row title="Data" detail="Export, restore and reset" onClick={()=>setScreen('data')}/><Row title="Accessibility" detail="Motion and interaction preferences" onClick={()=>setScreen('accessibility')}/><Row title="About & diagnostics" detail="Build state and health foundation" onClick={()=>setScreen('about')}/></nav>}
{screen==='workout'&&<nav className="settings-navigation"><Row title="Rest timer" detail="Automatic start, background alarm, sound and vibration" onClick={()=>setScreen('timer')}/><div className="settings-disabled-row"><span><strong>Set entry</strong><small>Additional sets remain deliberately low emphasis in workout cards.</small></span></div><div className="settings-disabled-row"><span><strong>Session behaviour</strong><small>Completed-session management lives in Profile → Session history.</small></span></div></nav>}
{screen==='timer'&&<TimerSettingsPanel timer={database.settings.restTimer} onUpdate={patch=>onUpdateSettings({restTimer:patch})}/>} {screen==='data'&&<DataSettingsPanel database={database} onReset={onReset}/>} {screen==='units'&&<section className="settings-detail-section"><h3>{database.profile.units==='kg'?'Kilograms':'Pounds'}</h3><p>Tracking semantics remain independent of the display unit.</p></section>} {screen==='notifications'&&<section className="settings-detail-section"><h3>Workout feedback</h3><p>Timer delivery is configured under Workout → Rest timer.</p></section>} {screen==='accessibility'&&<section className="settings-detail-section"><h3>System preferences respected</h3><p>Reduced Motion is detected from Android/browser preferences.</p></section>} {screen==='about'&&<section className="settings-detail-section"><h3>Phase 2 parity build</h3><p>The complete state remains offline in IndexedDB.</p><div className="settings-status-row"><span>Schema</span><strong>v{database.schemaVersion}</strong></div></section>}
</aside></div>}
